exec_once:
 execs:
  Install Jenkins:
   name: Install Jenkins
   timeout: "2000"
   command: |
     #!/usr/bin/env bash
     wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
     echo "deb https://pkg.jenkins.io/debian-stable binary/" >> /etc/apt/sources.list
     apt-get update
     apt-get install -y jenkins
     service jenkins start
